### ISSUE TITLE
Add new email-id for sending out confirmations

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/Car-Pool#10] opened 2019-02-25 20:06 UTC
The email id used currently in proj/settings.py has been blocked. Create a new one and keeps its id password out of the main files (preferably create a json file) and add the json file to gitignore, so that no one has access to that email id.. and only admins know it.

**Comment by vsvipul** [comment] 2019-02-25 20:06
@kpbot add "good first issue" "help wanted"

**Comment by Varunvaruns9** [comment] 2019-06-20 11:06
Closed as a duplicate of #12

**Closed as completed by Varunvaruns9** 2019-06-20 11:06 UTC
Labels: help wanted, good first issue
